name: Export

on:
  push:
  pull_request:

jobs:
  export:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    container:
      image: docker.io/setsoft/kicad_auto:dev_k6
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: zmk-uno.kibot.yaml
      - name: Archive Gerber ZIP
        uses: actions/upload-artifact@v2
        with:
          name: jlc
          path: JLCPCB/zmk-uno-JLCPCB.zip
      - name: Archive Positions/BOM
        uses: actions/upload-artifact@v2
        with:
          name: jlc
          path: zmk-uno_*jlc.csv
